workflows:
  capacitor-android:
    name: Capacitor Android Build
    max_build_duration: 30

    environment:
      node: 22

    scripts:
      - npm install
      - npm run build
      - npx cap sync android
      - cd android && ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
